name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Package with PyInstaller
      run: pyinstaller --onefile --name CleanSweep main.py

    - name: Prepare artifacts
      run: |
        mkdir artifacts
        cp dist/CleanSweep.exe artifacts/
        cp 清理配置.txt artifacts/
        cp README.md artifacts/

    - name: Create zip
      run: |
        cd artifacts
        powershell Compress-Archive -Path * -DestinationPath ../CleanSweep.zip

    - name: Archive results
      uses: actions/upload-artifact@v3
      with:
        name: win-x64
        path: CleanSweep.zip
